FROM node:17-alpine AS builder

WORKDIR /app

COPY package.json .

COPY package-lock.json .

RUN npm install --legacy-peer-deps

COPY . .

RUN yarn build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/build .

COPY client-nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

STOPSIGNAL SIGQUIT

CMD ["nginx", "-g", "daemon off;"]
