export default [
  {
    id: 1,
    title: "r/mildlyinteresting",
    description: "blah blah",
    coverImg: "logo.svg",
    stats: {
      members: 20,
      online: 6,
    },
    isJoined: false,
    rankChange: 2,
  },
  {
    id: 2,
    title: "r/funny",
    description: "blah blah haha",
    coverImg: "funny.png",
    stats: {
      members: 200,
      online: 60,
    },
    isJoined: true,
    rankChange: 1,
  },
  {
    id: 3,
    title: "r/space",
    description: "blah blah space",
    coverImg: "logo.svg",
    stats: {
      members: 203,
      online: 63,
    },
    isJoined: false,
    rankChange: 7,
  },
  {
    id: 1,
    title: "r/mildlyinteresting",
    description: "blah blah",
    coverImg: "logo.svg",
    stats: {
      members: 20,
      online: 6,
    },
    isJoined: false,
    rankChange: 15,
  },
  {
    id: 2,
    title: "r/funny",
    description: "blah blah haha",
    coverImg: "funny.png",
    stats: {
      members: 200,
      online: 60,
    },
    isJoined: true,
    rankChange: 70,
  },
  {
    id: 3,
    title: "r/space",
    description: "blah blah space",
    coverImg: "logo.svg",
    stats: {
      members: 203,
      online: 63,
    },
    isJoined: false,
    rankChange: 17,
  },
  {
    id: 1,
    title: "r/mildlyinteresting",
    description: "blah blah",
    coverImg: "logo.svg",
    stats: {
      members: 20,
      online: 6,
    },
    isJoined: false,
    rankChange: 5,
  },
  {
    id: 2,
    title: "r/funny",
    description: "blah blah haha",
    coverImg: "funny.png",
    stats: {
      members: 200,
      online: 60,
    },
    isJoined: true,
    rankChange: 26,
  },
  {
    id: 3,
    title: "r/space",
    description: "blah blah space",
    coverImg: "logo.svg",
    stats: {
      members: 203,
      online: 63,
    },
    isJoined: false,
    rankChange: 20,
  },
  {
    id: 1,
    title: "r/mildlyinteresting",
    description: "blah blah",
    coverImg: "logo.svg",
    stats: {
      members: 20,
      online: 6,
    },
    isJoined: false,
    rankChange: 14,
  },
  {
    id: 2,
    title: "r/funny",
    description: "blah blah haha",
    coverImg: "funny.png",
    stats: {
      members: 200,
      online: 60,
    },
    isJoined: true,
    rankChange: 23,
  },
  {
    id: 3,
    title: "r/space",
    description: "blah blah space",
    coverImg: "logo.svg",
    stats: {
      members: 203,
      online: 63,
    },
    isJoined: false,
    rankChange: 55,
  },
  {
    id: 1,
    title: "r/mildlyinteresting",
    description: "blah blah",
    coverImg: "logo.svg",
    stats: {
      members: 20,
      online: 6,
    },
    isJoined: false,
    rankChange: 2,
  },
  {
    id: 2,
    title: "r/funny",
    description: "blah blah haha",
    coverImg: "funny.png",
    stats: {
      members: 200,
      online: 60,
    },
    isJoined: true,
    rankChange: 12,
  },
  {
    id: 3,
    title: "r/space",
    description: "blah blah space",
    coverImg: "logo.svg",
    stats: {
      members: 203,
      online: 63,
    },
    isJoined: false,
    rankChange: 33,
  },
];
